version: '3.7'

services:
  gobl:
    image: 'git.reedcat.net:5050/dpi/images/go:221110'
    user: "${USERID}"
    tty: true
    stdin_open: true
    volumes:
      - ./cache:/.cache
      - ./go:/go
      - ./src:/var/qre
    working_dir: /var/qre
